package com.domain;

public class OrederGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oreder_goods.id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oreder_goods.order_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oreder_goods.goods_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oreder_goods.goods_num
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String goodsNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oreder_goods.id
     *
     * @return the value of oreder_goods.id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oreder_goods.id
     *
     * @param id the value for oreder_goods.id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oreder_goods.order_id
     *
     * @return the value of oreder_goods.order_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oreder_goods.order_id
     *
     * @param orderId the value for oreder_goods.order_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oreder_goods.goods_id
     *
     * @return the value of oreder_goods.goods_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oreder_goods.goods_id
     *
     * @param goodsId the value for oreder_goods.goods_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oreder_goods.goods_num
     *
     * @return the value of oreder_goods.goods_num
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oreder_goods.goods_num
     *
     * @param goodsNum the value for oreder_goods.goods_num
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setGoodsNum(String goodsNum) {
        this.goodsNum = goodsNum == null ? null : goodsNum.trim();
    }
}