package com.domain;

public class Picture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.id
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.goods_id
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.picture
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.id
     *
     * @return the value of picture.id
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.id
     *
     * @param id the value for picture.id
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.goods_id
     *
     * @return the value of picture.goods_id
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.goods_id
     *
     * @param goodsId the value for picture.goods_id
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.picture
     *
     * @return the value of picture.picture
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.picture
     *
     * @param picture the value for picture.picture
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }
}