package com.domain;

public class TbAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.address_id
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.username
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.address
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.address_id
     *
     * @return the value of tb_address.address_id
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.address_id
     *
     * @param addressId the value for tb_address.address_id
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.username
     *
     * @return the value of tb_address.username
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.username
     *
     * @param username the value for tb_address.username
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.address
     *
     * @return the value of tb_address.address
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.address
     *
     * @param address the value for tb_address.address
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}