package com.domain;

public class TbBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.brand_name
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.goods_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.type_1
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String type1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.type_2
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String type2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.picture
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.id
     *
     * @return the value of tb_brand.id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.id
     *
     * @param id the value for tb_brand.id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.brand_name
     *
     * @return the value of tb_brand.brand_name
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.brand_name
     *
     * @param brandName the value for tb_brand.brand_name
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.goods_id
     *
     * @return the value of tb_brand.goods_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.goods_id
     *
     * @param goodsId the value for tb_brand.goods_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.type_1
     *
     * @return the value of tb_brand.type_1
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getType1() {
        return type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.type_1
     *
     * @param type1 the value for tb_brand.type_1
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setType1(String type1) {
        this.type1 = type1 == null ? null : type1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.type_2
     *
     * @return the value of tb_brand.type_2
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.type_2
     *
     * @param type2 the value for tb_brand.type_2
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setType2(String type2) {
        this.type2 = type2 == null ? null : type2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.picture
     *
     * @return the value of tb_brand.picture
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.picture
     *
     * @param picture the value for tb_brand.picture
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }
}