package com.domain;

public class TbCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.user_name
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.goods_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.goods_number
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private Integer goodsNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.id
     *
     * @return the value of tb_cart.id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.id
     *
     * @param id the value for tb_cart.id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.user_name
     *
     * @return the value of tb_cart.user_name
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.user_name
     *
     * @param userName the value for tb_cart.user_name
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.goods_id
     *
     * @return the value of tb_cart.goods_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.goods_id
     *
     * @param goodsId the value for tb_cart.goods_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.goods_number
     *
     * @return the value of tb_cart.goods_number
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.goods_number
     *
     * @param goodsNumber the value for tb_cart.goods_number
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }
}