package com.domain;

public class TbGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_id
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_name
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_freenum
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String goodsFreenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_type
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_price
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_discribes
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String goodsDiscribes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_id
     *
     * @return the value of tb_goods.goods_id
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_id
     *
     * @param goodsId the value for tb_goods.goods_id
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_name
     *
     * @return the value of tb_goods.goods_name
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_name
     *
     * @param goodsName the value for tb_goods.goods_name
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_freenum
     *
     * @return the value of tb_goods.goods_freenum
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getGoodsFreenum() {
        return goodsFreenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_freenum
     *
     * @param goodsFreenum the value for tb_goods.goods_freenum
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setGoodsFreenum(String goodsFreenum) {
        this.goodsFreenum = goodsFreenum == null ? null : goodsFreenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_type
     *
     * @return the value of tb_goods.goods_type
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_type
     *
     * @param goodsType the value for tb_goods.goods_type
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_price
     *
     * @return the value of tb_goods.goods_price
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_price
     *
     * @param goodsPrice the value for tb_goods.goods_price
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setGoodsPrice(String goodsPrice) {
        this.goodsPrice = goodsPrice == null ? null : goodsPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_discribes
     *
     * @return the value of tb_goods.goods_discribes
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getGoodsDiscribes() {
        return goodsDiscribes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_discribes
     *
     * @param goodsDiscribes the value for tb_goods.goods_discribes
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setGoodsDiscribes(String goodsDiscribes) {
        this.goodsDiscribes = goodsDiscribes == null ? null : goodsDiscribes.trim();
    }
}