package com.domain;

public class TbMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.UserName
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.TrueName
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String truename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.PassWord
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.CardNO
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String cardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.CardType
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String cardtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.Tel
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.Email
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.Type
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.default_address
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    private Integer defaultAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.UserName
     *
     * @return the value of tb_member.UserName
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.UserName
     *
     * @param username the value for tb_member.UserName
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.TrueName
     *
     * @return the value of tb_member.TrueName
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.TrueName
     *
     * @param truename the value for tb_member.TrueName
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setTruename(String truename) {
        this.truename = truename == null ? null : truename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.PassWord
     *
     * @return the value of tb_member.PassWord
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.PassWord
     *
     * @param password the value for tb_member.PassWord
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.CardNO
     *
     * @return the value of tb_member.CardNO
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.CardNO
     *
     * @param cardno the value for tb_member.CardNO
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.CardType
     *
     * @return the value of tb_member.CardType
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.CardType
     *
     * @param cardtype the value for tb_member.CardType
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype == null ? null : cardtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.Tel
     *
     * @return the value of tb_member.Tel
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.Tel
     *
     * @param tel the value for tb_member.Tel
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.Email
     *
     * @return the value of tb_member.Email
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.Email
     *
     * @param email the value for tb_member.Email
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.Type
     *
     * @return the value of tb_member.Type
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.Type
     *
     * @param type the value for tb_member.Type
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_member.default_address
     *
     * @return the value of tb_member.default_address
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public Integer getDefaultAddress() {
        return defaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_member.default_address
     *
     * @param defaultAddress the value for tb_member.default_address
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    public void setDefaultAddress(Integer defaultAddress) {
        this.defaultAddress = defaultAddress;
    }
}