package com.domain;

import java.util.Date;

public class TbOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_time
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.username
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.address
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_price
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_status
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    private String orderStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_id
     *
     * @return the value of tb_order.order_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_id
     *
     * @param orderId the value for tb_order.order_id
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_time
     *
     * @return the value of tb_order.order_time
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_time
     *
     * @param orderTime the value for tb_order.order_time
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.username
     *
     * @return the value of tb_order.username
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.username
     *
     * @param username the value for tb_order.username
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.address
     *
     * @return the value of tb_order.address
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.address
     *
     * @param address the value for tb_order.address
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_price
     *
     * @return the value of tb_order.order_price
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_price
     *
     * @param orderPrice the value for tb_order.order_price
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setOrderPrice(String orderPrice) {
        this.orderPrice = orderPrice == null ? null : orderPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_status
     *
     * @return the value of tb_order.order_status
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_status
     *
     * @param orderStatus the value for tb_order.order_status
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }
}