package com.dao;

import com.domain.OrederGoods;
import com.domain.OrederGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrederGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    long countByExample(OrederGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    int deleteByExample(OrederGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    int insert(OrederGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    int insertSelective(OrederGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    List<OrederGoods> selectByExample(OrederGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    OrederGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrederGoods record, @Param("example") OrederGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    int updateByExample(@Param("record") OrederGoods record, @Param("example") OrederGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    int updateByPrimaryKeySelective(OrederGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oreder_goods
     *
     * @mbg.generated Fri Jul 27 14:24:36 CST 2018
     */
    int updateByPrimaryKey(OrederGoods record);
}