package com.dao;

import com.domain.TbBrand;
import com.domain.TbBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    long countByExample(TbBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    int deleteByExample(TbBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    int insert(TbBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    int insertSelective(TbBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    List<TbBrand> selectByExample(TbBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    TbBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbBrand record, @Param("example") TbBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    int updateByExample(@Param("record") TbBrand record, @Param("example") TbBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    int updateByPrimaryKeySelective(TbBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Sun Jul 29 17:10:38 CST 2018
     */
    int updateByPrimaryKey(TbBrand record);
}