package com.dao;

import com.domain.TbCart;
import com.domain.TbCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    long countByExample(TbCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    int deleteByExample(TbCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    int insert(TbCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    int insertSelective(TbCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    List<TbCart> selectByExample(TbCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    TbCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbCart record, @Param("example") TbCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    int updateByExample(@Param("record") TbCart record, @Param("example") TbCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(TbCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cart
     *
     * @mbg.generated Sat Jul 28 15:25:22 CST 2018
     */
    int updateByPrimaryKey(TbCart record);
}