package com.dao;

import com.domain.TbComment;
import com.domain.TbCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    long countByExample(TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int deleteByExample(TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int insert(TbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int insertSelective(TbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    List<TbComment> selectByExample(TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    TbComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbComment record, @Param("example") TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int updateByExample(@Param("record") TbComment record, @Param("example") TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int updateByPrimaryKeySelective(TbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int updateByPrimaryKey(TbComment record);
}