package com.dao;

import com.domain.TbMember;
import com.domain.TbMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    long countByExample(TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int deleteByExample(TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int insert(TbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int insertSelective(TbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    List<TbMember> selectByExample(TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    TbMember selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbMember record, @Param("example") TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int updateByExample(@Param("record") TbMember record, @Param("example") TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int updateByPrimaryKeySelective(TbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbg.generated Thu Aug 02 11:38:29 CST 2018
     */
    int updateByPrimaryKey(TbMember record);
}